version: 2
updates:
  # Node/npm for candidate client
  - package-ecosystem: "npm"
    directory: "/apps/candidate-client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    ignore:
      - dependency-name: "*"
        versions: []
    # Auto-merge patch updates
    automerged_updates:
      - match:
          update_type: "version-update:semver-patch"

  # Node/npm for recruiter client
  - package-ecosystem: "npm"
    directory: "/apps/recruiter-client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    automerged_updates:
      - match:
          update_type: "version-update:semver-patch"

  # .NET Core / NuGet for server
  - package-ecosystem: "nuget"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    automerged_updates:
      - match:
          update_type: "version-update:semver-patch"
